#!/usr/bin/env python3

import os
import json
import platform


def readFile():
    File = open('./archive/flag', 'r', encoding='UTF-8')
    c = File.read()
    File.close()
    return int(c)


def saveFile(q):
    q = str(q)
    File = open('./archive/flag', 'w', encoding='UTF-8')
    File.write(q)
    File.close()
    return


def main():
    File = open("./archive/data", 'r', encoding='UTF-8')
    sys = platform.system()
    if (sys == "Windows"):
        CLS = "cls"
    else:
        CLS = "clear"
    content = File.read()
    File.close()
    content = json.loads(content)
    t = readFile()
    while t < len(content):
        i = content[t]
        while True:
            os.system(CLS)
            print(t + 1, "/", len(content))
            print(i["Description"])
            print(i["ChoiceA"])
            print(i["ChoiceB"])
            print(i["ChoiceC"])
            print(i["ChoiceD"])
            answer = input("请输入答案:")
            if answer == i["Answer"]:  # 答案正确
                break
        t = t + 1
        saveFile(t)  # 存档
    print("题库已刷完！")


if __name__ == "__main__":
    main()
